auth:
  postgresPassword: "hotelier"
  username: "hotelier"
  database: "hotelierdb"
  existingSecret: ""

primary:
  initdbScripts:
    "01-create-dbs.sql": |
      CREATE DATABASE hotelier_accommodation;
      CREATE DATABASE hotelier_availability;
      CREATE DATABASE hotelier_identity;
      CREATE DATABASE hotelier_rating;
      CREATE DATABASE hotelier_reservation;

resources:
  requests:
    cpu: "1"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "1Gi"
