# Simplified - only needs RabbitMQ
replicaCount: 1
image:
  repository: localhost:30500/hotelier-cdn-service
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "1"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "1Gi"

env:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger.observability.svc.cluster.local:4317"
  Rabbit__Host: "rabbitmq.databases.svc.cluster.local"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: "nginx"
  hosts:
    - host: "minikube.local"
      paths:
        - path: "/cdn"
          pathType: Prefix

serviceMonitor:
  enabled: false
  interval: 30s
