replicaCount: 1

image:
  repository: hotelier-accommodation-service
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "1"
    memory: "1Gi"
  limits:
    cpu: "1"
    memory: "1Gi"

env:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  ConnectionStrings__Default: "Host=postgresql.databases.svc.cluster.local;Database=hotelier_reservation;Username=hotelier;Password=hotelier;Port=5432"
  Rabbit__Host: "rabbitmq.databases.svc.cluster.local"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: "minikube.local"
      paths:
        - path: "/reservation"
          pathType: Prefix

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

serviceMonitor:
  enabled: true
  interval: 30s
