replicaCount: 1

image:
  repository: localhost:30500/hotelier-notification-service
  tag: "latest"
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: "0.5"
    memory: "512Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

env:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_URLS: "http://+:8080"
  ConnectionStrings__Mongo: "mongodb://hotelier:hotelier@mongodb.databases.svc.cluster.local:27017/hotelier_notification?authSource=admin"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://jaeger.observability.svc.cluster.local:4317"
  Rabbit__Host: "rabbitmq.databases.svc.cluster.local"

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  className: "nginx"
  hosts:
    - host: "minikube.local"
      paths:
        - path: "/notification"
          pathType: Prefix

livenessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5

serviceMonitor:
  enabled: false
  interval: 30s
